version: '3'
services:
  profile-experience-app-container:
    image: experience:latest
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - /data/profile-experience-app
    ports:
      - "8080:8080"